version: '3'

services:
  mysql:
    # use mysql image from docker hub
    image: mysql
    # envirnoment variables for mysql server startup
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    # expose port 3306 to host machine
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    # health check for mysql container to wait for mysql to start
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  app:
    # use docker image
    image: badrannn/internship-task:latest
    build:
    # build docker image from current directory
      context: .
    # use dockerfile in current directory
      dockerfile: Dockerfile
    # environment variables for app
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASS=${MYSQL_PASS}
      - MYSQL_PORT=${MYSQL_PORT}
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy
