version: '3'

services:
  mysql:
    # use mysql image from docker hub
    image: mysql
    # envirnoment variables for mysql server startup
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: internship
    # expose port 3306 to host machine
    ports:
      - "3306:3306"
    # health check for mysql container to wait for mysql to start
    healthcheck:
      test: mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
  app:
    build:
    # build docker image from current directory
      context: .
    # 
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MYSQL_PORT=3306
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy
